name: Publish NuGet Package

on:
    push:
        tags:
            - "v*.*.*"

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0.x"

            - name: Restore dependencies
              run: dotnet restore

            - name: Pack
              run: dotnet pack -c Release -o out

            - name: Push to GitHub Packages
              run: dotnet nuget push "out/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }}
